global:
  scrape_interval: 15s
  external_labels:
    monitor: 'temporal-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:9091
        labels:
          group: 'sdk-metrics'
