---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: inventory   # Name of the resource
  labels:
    app: inventory
spec:
  ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
