apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: temporal-shop-monitor
  labels:
    team: sa
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: temporal-shop
  endpoints:
  - port: metrics
