apiVersion: 1

datasources:
  - name: 'temporal-prometheus'
    type: 'prometheus'
    orgId: 1
    url: 'http://prometheus:9090'
    isDefault: true
    version: 1
    editable: true
    basicAuth: false
