// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	ID string `json:"id"`
}

type CartItem struct {
	ProductID string `json:"productId"`
}

type Game struct {
	ID       string `json:"id"`
	Product  string `json:"product"`
	Category string `json:"category"`
	ImageURL string `json:"image_url"`
	Price    string `json:"price"`
}

type Games struct {
	Items []*Game `json:"items"`
}

type Shopper struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
