// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Cart struct {
	ID        string      `json:"id"`
	ShopperID string      `json:"shopperId"`
	Items     []*CartItem `json:"items"`
	Subtotal  *string     `json:"subtotal"`
	TaxRate   *string     `json:"taxRate"`
	Total     *string     `json:"total"`
	Tax       *string     `json:"tax"`
	Timestamp *time.Time  `json:"timestamp"`
}

type CartInput struct {
	CartID    string `json:"cartId"`
	ShopperID string `json:"shopperId"`
}

type CartItem struct {
	ProductID string `json:"productId"`
	Quantity  int    `json:"quantity"`
	Subtotal  string `json:"subtotal"`
	Price     string `json:"price"`
	Title     string `json:"title"`
	Category  string `json:"category"`
}

type CartItemInput struct {
	ProductID string `json:"productId"`
	Quantity  int    `json:"quantity"`
}

type CartSubscriptionInput struct {
	CartID string  `json:"cartId"`
	Topic  *string `json:"topic"`
}

type Game struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Category string `json:"category"`
	ImageURL string `json:"imageUrl"`
	Price    string `json:"price"`
}

type Inventory struct {
	Categories []string `json:"categories"`
	Games      []*Game  `json:"games"`
}

type InventoryInput struct {
	Category *string `json:"category"`
}

type Ping struct {
	Timestamp *time.Time `json:"timestamp"`
	Value     *string    `json:"value"`
}

type PingInput struct {
	Value     *string    `json:"value"`
	Timestamp *time.Time `json:"timestamp"`
}

type Pong struct {
	Timestamp *time.Time `json:"timestamp"`
	Value     *string    `json:"value"`
}

type SetCartItemsInput struct {
	CartID string           `json:"cartId"`
	Items  []*CartItemInput `json:"items"`
}

type Shopper struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	InventoryID string `json:"inventoryId"`
	CartID      string `json:"cartId"`
}

type ShopperInput struct {
	ShopperID *string `json:"shopperId"`
}

type User struct {
	Email string  `json:"email"`
	Token *string `json:"token"`
	Ok    bool    `json:"ok"`
}

type UserInput struct {
	Token *string `json:"token"`
}
