name: Temporal Shop Build Pipeline
on:
  push:
    branches:
      - svelteify
#  pull_request:
#      - main
env:
  APP_NAME: temporal-shop
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 429214323166
  CLUSTER_NAME: sa-prod
  GH_ACTIONS_ROLE: arn:aws:iam::429214323166:role/github-actions-role
  ECR_REPOSITORY: temporal-shop/web
  SLACK_CHANNEL: C038377FSCF #team-gtm
  GOPRIVATE: github.com/temporalio
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)
  S3_BUCKET: temporal-sa
jobs:
  cfg:
    runs-on: temporal-shop #this should be in the CR created for the runner
    outputs:
      s3-dir: ${{ steps.s3.outputs.dir }}
      s3-builds-dir: ${{ steps.builds.outputs.dir }}
      s3-builds-app-dir: ${{ steps.builds-app.outputs.dir }}
      s3-app-dir: ${{ steps.app.outputs.dir }}
      s3-app-prefix: ${{ steps.app-prefix.dir }}
    steps:
      - id: s3
        run: echo "dir=s3://${{ env.S3_BUCKET }}/${{ env.APP_NAME }}" >> $GITHUB_OUTPUT
      - id: builds
        run: echo "dir=${{ steps.s3.outputs.dir }}/builds/${{ env.SHORT_SHA }}" >> $GITHUB_OUTPUT
      - id: app-prefix
        run: echo "dir=${{ env.APP_NAME }}/app" >> $GITHUB_OUTPUT
      - id: builds-app
        run: echo "dir=${{ steps.builds.outputs.dir }}/app" >> $GITHUB_OUTPUT
      - id: app
        run: echo "dir=s3://${{ env.S3_BUCKET }}/${{ steps.app-prefix.outputs.dir }}" >> $GITHUB_OUTPUT
  ui:
    needs: [cfg]
    runs-on: temporal-shop #this should be in the CR created for the runner
    permissions:
      id-token: write
      contents: read
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.GH_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: asdf
        id: asdf
        uses: mnichols/asdf-composite-action@v1
      - name: dependencies
        run: |
          cd web/ui && npm i
#      - name: test
#        run: |
#          cd web/ui && npx playwright install && npm run test
      - name: build
        run: cd web/ui && npm run build
      - name: store ui artifact
        run: aws s3 sync web/bff/generated ${{ needs.cfg.outputs.s3-builds-app-dir }}
  bff:
    needs: [cfg]
    runs-on: temporal-shop #this should be in the CR created for the runner
    permissions:
      id-token: write
      contents: read
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.GH_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
#      - name: asdf
#        id: asdf
#        uses: mnichols/asdf-composite-action@v1
#      - name: dependencies
#        run: cd web && go mod tidy && go mod verify
#      - name: lint
#        run: cd web && golangci-lint run
#      - name: test
#        run: cd web && go test -race -timeout=5m -cover -count=1  ./...
  deploy:
    runs-on: temporal-shop #this should be in the CR created for the runner
    needs: [cfg,ui,bff]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.GH_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: asdf
        id: asdf
        uses: mnichols/asdf-composite-action@v1
      - name: login to amazon ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push to AWS ECR
        id: build-image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: temporal-shop/web
          addLatest: true
          # tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          registry: ${{ steps.login-ecr.outputs.registry }}
          dockerfile: Dockerfile.bff
      - name: split tags
        uses: jungwinter/split@v2
        id: split
        with:
          separator: ','
          msg: ${{ steps.build-image.outputs.tags }}
      - name: update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --role-arn ${{ env.GH_ACTIONS_ROLE }} --region ${{ env.AWS_REGION }}
        shell: bash
      - name: deploy bff
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          CTX=$(kubectl config current-context)
          IMG=${{ steps.build-image.outputs.imageFullName }}:${{ steps.split.outputs._0 }}
          echo "deploying to $CTX => $IMG"
          $(cd kustomize/web/overlays/prod && \
            kustomize edit set image amazonaws.com/web="$IMG")

          kustomize build kustomize/web/overlays/prod | kubectl apply -f -
      - name: deploy ui
        run: |
          aws s3 sync ${{ needs.cfg.outputs.s3-builds-app-dir }} ${{ needs.cfg.outputs.s3-app-dir }}
          $(aws s3api list-objects --bucket ${{ env.S3_BUCKET }} \
            --prefix ${{ needs.cfg.output.app-prefix }} \
            --query 'Contents[].[Key]' \
            --output text | xargs -n 1 -P 10 \
            aws s3api put-object-tagging --bucket ${{ env.S3_BUCKET }} \
            --tagging 'TagSet=[{Key=security,Value=public}]' --key)
      - name: clean artifacts
        run: aws s3 rm --recursive ${{ needs.cfg.outputs.s3-builds-dir }}