name: Temporal Shop Build Pipeline
on:
  push:
    branches:
      - main
      - small-fixes
#  pull_request:
#      - main
env:
  APP_NAME: temporal-shop
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 429214323166
  CLUSTER_NAME: sa-prod
  GH_ACTIONS_ROLE: arn:aws:iam::429214323166:role/github-actions-role
  #ECR_REPOSITORY: temporal-shop/web
  SLACK_CHANNEL: C038377FSCF #team-gtm
  GOPRIVATE: github.com/temporalio
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)
  S3_BUCKET: temporal-sa
jobs:
  cfg:
    runs-on: temporal-shop #this should be in the CR created for the runner
    outputs:
      s3-dir: ${{ steps.s3.outputs.dir }}
      s3-builds-dir: ${{ steps.builds.outputs.dir }}
      s3-builds-app-dir: ${{ steps.builds-app.outputs.dir }}
      s3-app-dir: ${{ steps.app.outputs.dir }}
      s3-app-prefix: ${{ steps.app-prefix.outputs.dir }}
    steps:
      - id: s3
        run: echo "dir=s3://${{ env.S3_BUCKET }}/${{ env.APP_NAME }}" >> $GITHUB_OUTPUT
      - id: builds
        run: echo "dir=${{ steps.s3.outputs.dir }}/builds/${{ env.SHORT_SHA }}" >> $GITHUB_OUTPUT
      - id: app-prefix
        run: echo "dir=${{ env.APP_NAME }}/app" >> $GITHUB_OUTPUT
      - id: builds-app
        run: echo "dir=${{ steps.builds.outputs.dir }}/app" >> $GITHUB_OUTPUT
      - id: app
        run: echo "dir=s3://${{ env.S3_BUCKET }}/${{ steps.app-prefix.outputs.dir }}" >> $GITHUB_OUTPUT
  domain:
    needs: [cfg]
    runs-on: temporal-shop #this should be in the CR created for the runner
    permissions:
      id-token: write
      contents: read
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.GH_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: asdf
        id: asdf
        uses: mnichols/asdf-composite-action@v1
      - name: dependency requirements
        run: |
          git config --global url."https://${{ secrets.PAT }}@github".insteadOf https://github
      - name: dependencies
        run: cd services/go && go mod tidy && go mod verify
      - name: lint
        run: cd services/go && golangci-lint run
      - name: test
        run: cd services/go && go test -race -timeout=5m -cover -count=1  ./...
  deploy:
    runs-on: temporal-shop #this should be in the CR created for the runner
    needs: [cfg,domain]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.GH_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: asdf
        id: asdf
        uses: mnichols/asdf-composite-action@v1
      - name: login to amazon ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: DOMAIN_Build_tag_push_to_AWS_ECR
        id: build-image-domain
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: temporal-shop/domain
          addLatest: true
          # tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          registry: ${{ steps.login-ecr.outputs.registry }}
          dockerfile: Dockerfile.domain
      - name: split tags
        uses: jungwinter/split@v2
        id: split-domain
        with:
          separator: ','
          msg: ${{ steps.build-image.outputs.tags }}
      - name: update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --role-arn ${{ env.GH_ACTIONS_ROLE }} --region ${{ env.AWS_REGION }}
        shell: bash
      - name: deploy domain
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          CTX=$(kubectl config current-context)
          IMG=${{ steps.build-image-domain.outputs.imageFullName }}:${{ steps.split-domain.outputs._0 }}
          echo "::notice title={deploying domain bin}::deploying to $CTX => $IMG"
          $(cd kustomize/domain/overlays/prod && \
            kustomize edit set image amazonaws.com/domain="$IMG")

          kustomize build kustomize/domain/overlays/prod | kubectl apply -f -